# Generated by Django 3.0.2 on 2020-01-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200, null=True)),
                ('bio', models.TextField(null=True)),
                ('avatar_url', models.CharField(max_length=255, null=True)),
                ('techs', models.TextField(null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
            ],
        ),
    ]
